from pydantic import BaseModel
from pydantic import Field


class ExtractedResume(BaseModel):
    """Structured resume data extracted from PDF using LLM parsing.

    Represents normalized candidate profile data with validated fields
    for skills, experience, education, and other resume sections.
    Generated by ResumeExtractor from raw PDF text.
    """

    full_name: str = Field(
        ...,
        description=(
            "Candidate's full name as extracted verbatim from the resume. "
            "No normalization or reordering applied."
        ),
    )
    email: str | None = Field(
        default=None,
        description=(
            "Primary email address extracted from the resume, if present. "
            "Expected to be a valid email format."
        ),
    )
    phone: str | None = Field(
        default=None,
        description=(
            "Phone number associated with the candidate as found in the resume. "
            "Stored in the original detected format, without normalization."
        ),
    )
    education: list[str] = Field(
        default_factory=list,
        description=(
            "Educational background entries extracted from the resume, including "
            "degrees, institutions, fields of study, and dates when available."
        ),
    )
    experience: list[str] = Field(
        default_factory=list,
        description=(
            "Professional experience entries extracted from the resume, including "
            "job titles, companies, responsibilities, and employment periods."
        ),
    )
    skills: list[str] = Field(
        default_factory=list,
        description=(
            "List of skills explicitly mentioned in the resume, including technical, "
            "professional, and soft skills. No categorization or deduplication applied."
        ),
    )
    projects: list[str] = Field(
        default_factory=list,
        description=(
            "Relevant projects extracted from the resume, including academic, "
            "or personal projects, with brief descriptions if provided."
        ),
    )
    certifications: list[str] = Field(
        default_factory=list,
        description=(
            "Certifications, licenses, or credentials explicitly listed in the resume, "
            "including issuing organizations when available."
        ),
    )
